      properties:
        environment:
          ENV_1: "VAL"
          ENV_2: "VAL"
        ports:
        - "30001:8888"
      requirements:
      - host:
          capability: "tosca.capabilities.QC.docker.Orchestrator"
          node: "kubernetes"
          relationship: "tosca.relationships.HostedOn"
      interfaces:
        Kubernetes:
          autoscale:
            inputs:
              horizontal_pod_autoscaler: "horizontal_pod_autoscaler.yml"
              repository: "https://github.com/QCAPI-DRIP/playbooks.git"
              resources:
              - "k8s/autoscale_service.yml"
          create:
            inputs:
              repository: "https://github.com/QCAPI-DRIP/playbooks.git"
              resources:
              - "k8s/create_service.yml"
          delete:
            inputs:
              repository: "https://github.com/QCAPI-DRIP/playbooks.git"
              resources:
              - "k8s/delete_service.yml"
          info:
            inputs:
              repository: "https://github.com/QCAPI-DRIP/playbooks.git"
              resources:
              - "k8s/get_info_service.yml"
          scale:
            inputs:
              replicas: 1
              repository: "https://github.com/QCAPI-DRIP/playbooks.git"
              resources:
              - "k8s/scale_service.yml"
      type: "tosca.nodes.QC.Container.Application.Docker"
      artifacts:
        image:
          file: FILE
          repository: "docker_hub"
          type: "tosca.artifacts.Deployment.Image.Container.Docker"
