NAME:
    type: tosca.nodes.QC.Container.Application.Docker
    properties:
        environment:
          ENV_1: VAL
          ENV_2: VAL
        ports:
          - "30000:8888"              
    artifacts:
        image:
            type: tosca.artifacts.Deployment.Image.Container.Docker
            file:  FILE
            repository: docker_hub                 
    interfaces:
        Kubernetes:
            delete:
                inputs:
                    repository: https://github.com/QCAPI-DRIP/playbooks.git
                    resources:
                        - k8s/delete_service.yml
            create:
                inputs:
                    repository: https://github.com/QCAPI-DRIP/playbooks.git
                    resources:
                        - k8s/create_service.yml
            scale:
                inputs:
                    repository: https://github.com/QCAPI-DRIP/playbooks.git
                    resources:
                        - k8s/scale_service.yml  
                    replicas: 1
            autoscale:
                inputs:
                    repository: https://github.com/QCAPI-DRIP/playbooks.git                
                    resources:
                        - k8s/autoscale_service.yml  
                    horizontal_pod_autoscaler: horizontal_pod_autoscaler.yml  
            info:
                inputs:
                    repository: https://github.com/QCAPI-DRIP/playbooks.git   
                    resources:
                        - k8s/get_info_service.yml      
